repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-docstring-first
    -   id: debug-statements
        exclude: bumpity.py$
    -   id: end-of-file-fixer
    -   id: name-tests-test
    -   id: trailing-whitespace
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.6
    hooks:
    -   id: ruff-check
        args: [--fix]
        exclude: ^test_data/
    -   id: ruff-format
        exclude: ^test_data/
-   repo: local
    hooks:
    -   id: detect-secrets
        name: Detect secrets
        language: python
        entry: detect-secrets-hook
        args: ['--baseline', '.secrets.baseline']
