# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: detect-secrets-ci

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python }}
    - uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
    - run: uv sync --frozen --python ${{ matrix.python }}
    - run: uv run coverage erase
    - run: uv run coverage run -m pytest --strict-markers tests
    # I don't want to write `pragma: no cover` for `for` loops that don't have
    # a case that doesn't enter the `for` loop. -_-"
    - run: uv run coverage report --show-missing --include=tests/* --fail-under 99
    - run: uv run coverage report --show-missing --include=testing/* --fail-under 100
    - run: uv run coverage report --show-missing --skip-covered --include=detect_secrets/* --fail-under 95
    - run: uv run ty check
    - run: uv run pre-commit run --all-files
